export const MOVIES_SAVED = 'MOVIES_SAVED';
export const MOVIES_SELECTED = 'MOVIES_SELECTED';
export const GENRE_SAVED = 'GENRE_SAVED';
export const FETCH_NEW_LIST_MOVIES = 'FETCH_NEW_LIST_MOVIES';
export const GENRE_AND_PAGE_RESETED = 'GENRE_AND_PAGE_RESETED';
export const MOVIE_CHANGED = 'MOVIE_CHANGED';
export const MOVIE_DELETED = 'MOVIE_DELETED';
export const SELECTED_MOVIES_INITIALIZED = 'SELECTED_MOVIES_INITIALIZED';